version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - my_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: crudDB
    volumes:
      - /docker/volumes/postgres:/var/lib/postgresql/data
  
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - my_network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - 5000:5000
    networks:
      - my_network
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/crudDB
    depends_on:
      - db

networks:
  my_network:
    driver: bridge
